let
    Origine = Csv.Document(Web.Contents("http://www.meteo.psu.edu/holocene/public_html/Mann/research/res_pages/ONLINE-PREPRINTS/Millennium/DATA/RECONS/nhem-recon.dat"),3,"",ExtraValues.Ignore,1252),
    #"Modifica tipo" = Table.TransformColumnTypes(Origine,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
    #"Rimosse colonne" = Table.RemoveColumns(#"Modifica tipo",{"Column1"}),
    #"Rinominate colonne" = Table.RenameColumns(#"Rimosse colonne",{{"Column2", "Year"}, {"Column3", "Reconstructed Temp Change"}}),
    #"Modificato tipo con impostazioni locali" = Table.TransformColumnTypes(#"Rinominate colonne", {{"Reconstructed Temp Change", type number}}, "en-US"),
    #"Merge di query eseguito" = Table.NestedJoin(#"Modificato tipo con impostazioni locali", {"Year"}, #"Instrumental Data", {"Year"}, "Instrumental Data", JoinKind.FullOuter),
    #"Tabella Instrumental Data espansa" = Table.ExpandTableColumn(#"Merge di query eseguito", "Instrumental Data", {"Year", "Instrumental Temp Change"}, {"Year.1", "Instrumental Temp Change"}),
    #"Aggiunta colonna indice" = Table.AddIndexColumn(#"Tabella Instrumental Data espansa", "Indice", 1000, 1, Int64.Type),
    #"Rimosse colonne1" = Table.RemoveColumns(#"Aggiunta colonna indice",{"Year", "Year.1"}),
    #"Modificato tipo" = Table.TransformColumnTypes(#"Rimosse colonne1",{{"Indice", type text}}),
    #"Rinominate colonne1" = Table.RenameColumns(#"Modificato tipo",{{"Indice", "Year"}}),
    #"Modificato tipo1" = Table.TransformColumnTypes(#"Rinominate colonne1",{{"Year", type date}}),
    #"Merge di query eseguito1" = Table.NestedJoin(#"Modificato tipo1", {"Year"}, Sigma, {"YEAR   "}, "Sigma", JoinKind.LeftOuter),
    #"Tabella Sigma espansa" = Table.ExpandTableColumn(#"Merge di query eseguito1", "Sigma", {"1 SIGMA    "}, {"1 SIGMA    "}),
    #"Rinominate colonne2" = Table.RenameColumns(#"Tabella Sigma espansa",{{"1 SIGMA    ", "Sigma"}}),
    #"Aggiunta colonna personalizzata" = Table.AddColumn(#"Rinominate colonne2", "Positive Variance", each [Reconstructed Temp Change] + [Sigma]),
    #"Aggiunta colonna personalizzata1" = Table.AddColumn(#"Aggiunta colonna personalizzata", "Negative Variance", each [Reconstructed Temp Change] - [Sigma]),
    #"Modificato tipo con impostazioni locali1" = Table.TransformColumnTypes(#"Aggiunta colonna personalizzata1", {{"Positive Variance", type number}}, "en-US"),
    #"Modificato tipo2" = Table.TransformColumnTypes(#"Modificato tipo con impostazioni locali1",{{"Negative Variance", type number}}),
    #"Modificato tipo con impostazioni locali2" = Table.TransformColumnTypes(#"Modificato tipo2", {{"Negative Variance", type number}}, "en-US"),
    #"Aggiunta colonna personalizzata2" = Table.AddColumn(#"Modificato tipo con impostazioni locali2", "Temp Average", each if [Instrumental Temp Change] = null then [Reconstructed Temp Change] else if [Reconstructed Temp Change] = null then [Instrumental Temp Change] else ([Instrumental Temp Change]+[Reconstructed Temp Change])/2),
    #"Modificato tipo con impostazioni locali3" = Table.TransformColumnTypes(#"Aggiunta colonna personalizzata2", {{"Temp Average", type number}}, "en-US"),
    #"passo1MAT" = Table.AddColumn(#"Modificato tipo con impostazioni locali3", "Date40YearBack", each Date.AddYears([Year],-40), type date),
    #"passo2MAT" = Table.Sort(#"passo1MAT",{{"Year", Order.Ascending}}),
    BufferedTable= Table.Buffer(#"passo2MAT"),
    #"passo3MAT" = Table.AddColumn(BufferedTable, "MAT", (x) => List.Average
(Table.SelectRows(BufferedTable, each [Year] >= x[Date40YearBack] and [Year] <= x[Year])[Temp Average]),type number),
    #"passo4MAT" = Table.RemoveColumns(#"passo3MAT",{"Date40YearBack"})
in
     #"passo4MAT"